basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Spider shop Restfull API using Gin Framework, Gorm orm and other libraries
  title: SpiderShop-Restfull-API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
